version: "3"
services:

  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    links:
      - postgres
    volumes:
          - "./notebooks:/notebooks"
          - "./data:/data"
    environment:
      TF_DOCKER_BUILD_PYTHON_VERSION: PYTHON3
      TF_DOCKER_BUILD_TYPE: CPU

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: data